/*
 * Automatically generated by Magic.
 */
CREATE TABLE requests(
  request_id integer not null primary key autoincrement,
  prompt text not null,
  completion text not null,
  created timestamp not null default current_timestamp
);

